In [1]:
import numpy as np

# Importing Numpy

In [2]:
arr = [6, 7, 8, 9]
print(type(arr))

<class 'list'>


In [6]:
a = np.array(arr)
print(a)
print(type(a))
print(a.shape)
print(a.dtype)

[6 7 8 9]
<class 'numpy.ndarray'>
(4,)
int32


In [5]:
arr1 = [6, 'abc', True, [1,2,3,4]]
a1 = np.array(arr1)

print(a1)
print(type(a1))
print(a1.shape)
print(a1.dtype)

[6 'abc' True list([1, 2, 3, 4])]
<class 'numpy.ndarray'>
(4,)
object


<ipython-input-5-879bad904ef7>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  a1 = np.array(arr1)


In [7]:
print(a.ndim)

1


In [9]:
b = np.array([[1,2,3], [4,5,6]])
print(b)
print(b.ndim)
print(b.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


# Inbuild functions

In [10]:
np.random.random((2,3))

array([[0.59770359, 0.81794707, 0.23799893],
       [0.41794403, 0.74003721, 0.69029583]])

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Intra-Operability 

In [14]:
c = np.array([[9,8,7],[1,2,3]])
d = np.array([[4,5,6],[9,8,7]])

In [15]:
c+d

array([[13, 13, 13],
       [10, 10, 10]])

In [16]:
c*d

array([[36, 40, 42],
       [ 9, 16, 21]])

In [17]:
5/d

array([[1.25      , 1.        , 0.83333333],
       [0.55555556, 0.625     , 0.71428571]])

In [18]:
c**2

array([[81, 64, 49],
       [ 1,  4,  9]], dtype=int32)

# Indexing

In [20]:
a

array([6, 7, 8, 9])

In [19]:
print(a[0])
print(a[3])

6
9


In [21]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
print(b[0,0])
print(b[1,2])

1
6


In [23]:
c

array([[9, 8, 7],
       [1, 2, 3]])

In [24]:
c[0,1]

8

In [25]:
d

array([[4, 5, 6],
       [9, 8, 7]])

In [26]:
d[1, 0:2]

array([9, 8])

In [28]:
e = np.array([[10,11,12],[13,14,15],[16,17,18],[19,20,21]])
e

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [29]:
e[:3, :2]

array([[10, 11],
       [13, 14],
       [16, 17]])

In [30]:
e[[2,0,3,1],[2,1,0,2]]

array([18, 11, 19, 15])

In [31]:
e[e>15]

array([16, 17, 18, 19, 20, 21])